### PR TITLE
Social media icons with brand colors on hover

### PR DESCRIPTION
**Pull request by HLFH**
Hi,

Quite same as Casper PR commit https://github.com/TryGhost/Casper/pull/200 but for Blog theme. 

According to http://brandcolors.net/,

IMHO, the "very dark grayish blue" color on hover of the social media icons is not fantastic and it could be a better secondary call-to-action by using the official brand colors on hover:
- #333333 for GitHub
- #55acee for Twitter
- #dd4b39 for Google+
- #3b5998 for Facebook

You could see the difference:
screenshot 2015-08-13 at 03 20 39

### CODE REVIEW

**Comment by JohnONolan** [comment]
Hey there, thanks for the great PR! The colours would need to be changed in the SASS file and properly processed, at the moment you've only changed them in the compressed CSS file.

**Comment by HLFH** [comment]
@JohnONolan Thanks. I did another commit. Is that ok?

**Comment by JohnONolan** [comment]
@HLFH - These styles are actually coming from the global stylesheet for Ghost.org - so they shouldn't be modified here on the blog, we'll have to change them upstream. If you want to do a new PR just to resolve the duplicate rel="stylesheet" I'd be happy to merge that though

**Comment by HLFH** [comment]
@JohnONolan Yes, this PR was a workaround. 

> we'll have to change them upstream 

Thanks in advance!

This is the new PR to resolve the duplicate rel="stylesheet": https://github.com/TryGhost/Blog/pull/7

**Pull request closed without merging**
